export const videosPerAlbumLinks = {
    mostaza: ["5yq2EAiys6E"],
    quilmesRock: ["YQERuBqKHJA"],
    contenidoMarcas: ["INrcISQVCRA"],
    sedalLollapalooza: ["QVsRLLJX4xg"],
    corrientes: [
      "K0d7rA5XUFQ",
      "-QjDFKxqqfY",
    ],
    entrevistas: ["GJmwo0tweMs", "fyATCA2qJd4"],
    gancia: ["P00A-p4llsU"],
    miami: [
      "FITjyNlCSvA",
      "RHQlh7CvsqI",
      "lNq_9S8q7k0",
    ],
    fila: ["Q7qYCD086X0"],
    pantene: ["6FMVSflMt_k"],
    tiktokActuacion: [
      "wIuckmx2Lk0",
      "TL668lU8c1A",
      "Oj7N7b_M-64",
      "_BHduOFLrVU?featufre=share",
      "_qNcOn_9fMY",
      "kmWHEssj4TI",
    ],
    tiktokBaile: [
      "ITUcUWMcn1Q",
      "ux0tiLQwfB0",
      "_R_3GlDhRnQ",
      "J8RcOKK84iU",
      "jjTYOzH0Ero",
      "ed9eBpAZAus",
      "PV6hCk5k90E",
      "LV5EhIUngUc",
      "DbZGkICRCjw",
      "KfJCa6BsgBw",
      "G1rdu3uxI9I",
      "hi1U270bXaI",
      "H7mZMuQiJxw",
      "KmaOZUaB23o",
      "7VcZreLmhXs",
    ],
    tiktokLifestyle: [
      "Z5ASLTFuuk4",
      "zQu1DpzhAm0",
      "a_zmbuOf0u0",
      "d06TSpF10Q0",
      "BA4m19bDJoE",
      "g3gnOpfTwSY",
    ],
  };
  